### PR TITLE
docs: Correct syntax for showing a script editor and rendering...

### PR DESCRIPTION
**Pull request by bjones1**
... the edited content to a graph.

Only respond to CustomEvent (not InputEvent) to avoid unnecessary graphviz renders.

Thanks for creating this -- what a great resource!

### CODE REVIEW

**Comment by bjones1** [comment]
@prantlf, would you enable CI by approving this workflow? I'd also like CI for my second PR (#4), since the changes there are code and not just docs.

Thanks for creating this!

**Comment by prantlf** [comment]
Thanks a lot for noticing this!

I'll consider replacing the custom `input` event in the next breaking-change release. I must've missed that the original `input` even was `composed` and bubbled out of the shadow DOM. It's confusing to trigger an event once more with the same type. The second event is triggered from CodeJar's onUpdate callback. That's why I'll probably rename it to `update`.

**Comment by prantlf** [comment]
> @prantlf, would you enable CI by approving this workflow? I'd also like CI for my second PR (#4), since the changes there are code and not just docs.
> 
> Thanks for creating this!

Thanks for the kind words!

Well, I tried to find where I should enable the CI for your PR, but I couldn't. After I rebased it using the GitHub UI, the pipeline was just triggered. Maybe because I tampered with your PR :-) Let's see if I find some button to permit the CI the next time.

**Comment by bjones1** [comment]
Sounds good, thanks for looking at this and producing this package!

**Pull request merged**
